apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: deepfacelab-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline_compilation_time: '2021-06-21T13:44:46.701186',
    pipelines.kubeflow.org/pipeline_spec: '{"inputs": [{"name": "youtube_url_target",
      "type": "String"}, {"name": "youtube_url_source", "type": "String"}], "name":
      "DeepFaceLab Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3}
spec:
  entrypoint: deepfacelab-pipeline
  templates:
  - name: clear-workspace-op
    container:
      args: []
      command:
      - sh
      - -ec
      - |
        program_path=$(mktemp)
        printf "%s" "$0" > "$program_path"
        python3 -u "$program_path" "$@"
      - |
        def clear_workspace_op(
        ):
            pass

        import argparse
        _parser = argparse.ArgumentParser(prog='Clear workspace op', description='')
        _parsed_args = vars(_parser.parse_args())

        _outputs = clear_workspace_op(**_parsed_args)
      image: gcr.io/kfserving/storage-initializer:v0.4.0
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
      annotations: {pipelines.kubeflow.org/component_spec: '{"implementation": {"container":
          {"args": [], "command": ["sh", "-ec", "program_path=$(mktemp)\nprintf \"%s\"
          \"$0\" > \"$program_path\"\npython3 -u \"$program_path\" \"$@\"\n", "def
          clear_workspace_op(\n):\n    pass\n\nimport argparse\n_parser = argparse.ArgumentParser(prog=''Clear
          workspace op'', description='''')\n_parsed_args = vars(_parser.parse_args())\n\n_outputs
          = clear_workspace_op(**_parsed_args)\n"], "image": "gcr.io/kfserving/storage-initializer:v0.4.0"}},
          "name": "Clear workspace op"}', pipelines.kubeflow.org/component_ref: '{}'}
  - name: deepfacelab-pipeline
    dag:
      tasks:
      - {name: clear-workspace-op, template: clear-workspace-op}
  arguments:
    parameters:
    - {name: youtube_url_target}
    - {name: youtube_url_source}
  serviceAccountName: pipeline-runner
